export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_GET_ITEM_SUCCESS = 'CART_GET_ITEM_SUCCESS'
export const CART_GET_ITEM_FAIL = 'CART_GET_ITEM_FAIL'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_INCREASE_ITEM = 'CART_INCREASE_ITEM'
export const CART_DECREASE_ITEM = 'CART_DECREASE_ITEM'
export const CART_DELETE = 'CART_DELETE'

