export const CATEGORY_ALL_REQUEST = "CATEGORY_ALL_REQUEST";
export const CATEGORY_ALL_SUCCESS = "CATEGORY_ALL_SUCCESS";
export const CATEGORY_ALL_FAIL = "CATEGORY_ALL_FAIL";

export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL";

export const CATEGORY_REMOVE_REQUEST = "CATEGORY_REMOVE_REQUEST";
export const CATEGORY_REMOVE_SUCCESS = "CATEGORY_REMOVE_SUCCESS";
export const CATEGORY_REMOVE_FAIL = "CATEGORY_REMOVE_FAIL";


