const PRODUCT_ALL_REQUEST = "PRODUCT_ALL_REQUEST";
const PRODUCT_ALL_SUCCESS = "PRODUCT_ALL_SUCCESS";
const PRODUCT_ALL_FAIL = "PRODUCT_ALL_FAIL";

const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

const PRODUCT_REMOVE_REQUEST = "PRODUCT_REMOVE_REQUEST";
const PRODUCT_REMOVE_SUCCESS = "PRODUCT_REMOVE_SUCCESS";
const PRODUCT_REMOVE_FAIL = "PRODUCT_REMOVE_FAIL";

const PRODUCT_ADD_COMMENT_REQUEST = 'PRODUCT_ADD_COMMENT_REQUEST'
const PRODUCT_ADD_COMMENT_SUCCESS = 'PRODUCT_ADD_COMMENT_SUCCESS'
const PRODUCT_ADD_COMMENT_FAIL = 'PRODUCT_ADD_COMMENT_FAIL'


export {
  PRODUCT_ALL_REQUEST,
  PRODUCT_ALL_SUCCESS,
  PRODUCT_ALL_FAIL,
  PRODUCT_DETAIL_REQUEST,
  PRODUCT_DETAIL_SUCCESS,
  PRODUCT_DETAIL_FAIL,
  PRODUCT_UPDATE_REQUEST,
  PRODUCT_UPDATE_SUCCESS,
  PRODUCT_UPDATE_FAIL,
  PRODUCT_CREATE_REQUEST,
  PRODUCT_CREATE_SUCCESS,
  PRODUCT_CREATE_FAIL,
  PRODUCT_REMOVE_REQUEST,
  PRODUCT_REMOVE_SUCCESS,
  PRODUCT_REMOVE_FAIL,
  PRODUCT_ADD_COMMENT_REQUEST,
  PRODUCT_ADD_COMMENT_SUCCESS,
  PRODUCT_ADD_COMMENT_FAIL
};
