const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';


export {
  USER_REGISTER_FAIL,
  USER_REGISTER_REQUEST,
  USER_REGISTER_SUCCESS,
  USER_LOGIN_REQUEST,
  USER_LOGIN_FAIL,
  USER_LOGIN_SUCCESS,
  USER_LOGOUT_REQUEST,
  USER_LOGOUT_SUCCESS,
  USER_LOGOUT_FAIL
};
